version: 0.2

env:
  variables:
    AWS_REGION: us-east-1
    AWS_ACCOUNT_ID: 479699168596
    ECR_REPO: far-registry
    IMAGE_TAG: latest

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_REGION |
        docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO

  build:
    commands:
      - mvn -B -DskipTests clean package
      - docker build -t bankapp:$IMAGE_TAG .
      - docker tag bankapp:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - docker push $REPOSITORY_URI:$IMAGE_TAG
